name: build
on: push
jobs:
  build:
    name: my joobbbbb
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]
    steps:
      - name: this is my first step - elida
        env:
          MY_VAR: Hi there! my name is
          FIRST_NAME: elida
          LAST_NAME: gomez
        run: echo $MY_VAR $FIRST_NAME $LAST_NAME
      - name: my second steps - elida
        if: success() //revisa si el paso anterior fue success
        run: echo "the previous step has finished successfully"

        
      
